# Generated by Django 5.1.1 on 2024-11-06 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('online_class', '0002_alter_onlineclass_adding_start_time'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('max_score', models.IntegerField()),
                ('online_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_class.onlineclass')),
            ],
        ),
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
                ('question_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questionanswer')),
            ],
        ),
    ]
