# Generated by Django 5.1.1 on 2024-09-29 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_private', models.BooleanField(default=True)),
                ('has_limit', models.BooleanField(default=False)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('invitational', models.BooleanField(blank=True)),
                ('password', models.CharField(max_length=100)),
                ('adding_start_time', models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 29, 6, 20, 14, 798482, tzinfo=datetime.timezone.utc))),
                ('adding_end_time', models.DateTimeField(blank=True)),
                ('students', models.ManyToManyField(blank=True, related_name='students', to='user.userprofile')),
                ('teachers', models.ManyToManyField(blank=True, related_name='teachers', to='user.userprofile')),
            ],
        ),
    ]
