# Generated by Django 5.1.1 on 2024-10-20 16:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_private', models.BooleanField(default=True)),
                ('has_limit', models.BooleanField(default=False)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('invitational', models.BooleanField(blank=True)),
                ('password', models.CharField(max_length=100)),
                ('adding_start_time', models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 20, 16, 33, 0, 472199, tzinfo=datetime.timezone.utc))),
                ('adding_end_time', models.DateTimeField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('mentors', models.ManyToManyField(blank=True, related_name='mentors', to='user.userprofile')),
                ('students', models.ManyToManyField(blank=True, related_name='students', to='user.userprofile')),
                ('teachers', models.ManyToManyField(blank=True, related_name='teachers', to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
                ('class_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_class.onlineclass')),
            ],
        ),
    ]
