# Generated by Django 5.1.1 on 2024-10-20 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('online_class', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('online_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_class.onlineclass')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_format', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('code', 'Code')], max_length=10)),
                ('has_time_limit', models.BooleanField(default=False)),
                ('has_upload_limit', models.BooleanField(default=False)),
                ('first_deadline', models.DateTimeField(blank=True)),
                ('second_deadline', models.DateTimeField(blank=True)),
                ('penalty_hour', models.IntegerField(blank=True)),
                ('penalty', models.IntegerField(blank=True)),
                ('upload_limit', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('in_bank', models.BooleanField(default=False)),
                ('max_score', models.IntegerField(default=100)),
                ('is_team', models.BooleanField(default=False)),
                ('teams_status', models.IntegerField(blank=True, null=True)),
                ('scoring_way', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='question_answers/')),
                ('text', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('users', models.ManyToManyField(to='user.userprofile')),
            ],
        ),
    ]
