# Generated by Django 5.1 on 2024-10-01 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_alter_onlineclass_adding_start_time_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onlineclass',
            name='adding_start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 1, 14, 21, 58, 973019, tzinfo=datetime.timezone.utc)),
        ),
    ]
